import { DarkTheme } from "@react-navigation/native";

import {
  accentPurple,
  accentPurpleDark,
  accentPurpleLight,
  activeSegment,
  amber,
  bg,
  border,
  borderEmphasized,
  borderLight,
  borderLoss,
  borderProfit,
  brand,
  brandDark,
  card,
  cardEmphasized,
  disabled,
  field,
  gradientGreen,
  gradientGreenGlow,
  gradientOrange,
  gradientRed,
  highEmText,
  loss,
  lossBg,
  lowEmText,
  midEmText,
  onActiveSegment,
  onPrimary,
  onSecondary,
  orangeDark,
  orangeDeep,
  primary,
  primaryGreenLight,
  primaryRedLight,
  primaryTapped,
  profit,
  profitBg,
  secondary,
  secondaryTapped,
  segmentedControl,
  tabActive,
  timerPurple,
  white,
} from "./app-colors";

export const darkTheme = {
  ...DarkTheme,
  colors: {
    ...DarkTheme.colors,
    tint: white,
    background: bg,
    backgroundSecondary: card,
    card,
    cardEmphasized,
    brand,
    brandDark,
    highEmText,
    midEmText,
    lowEmText,
    profitBg,
    profit,
    profitLight: primaryGreenLight,
    lossBg,
    loss,
    lossLight: primaryRedLight,
    primary,
    primaryTapped,
    onPrimary,
    secondary,
    secondaryTapped,
    onSecondary,
    segmentedControl,
    activeSegment,
    onActiveSegment,
    field,
    disabled,
    borderLight,
    border,
    borderEmphasized,
    borderProfit,
    borderLoss,
    tabActive,
    textPrimary: highEmText,
    textSecondary: midEmText,
    gradientRed,
    gradientOrange,
    gradientGreen,
    gradientGreenGlow,
    liquidLine: amber,
    liquidBorder: orangeDark,
    liquidBg: orangeDeep,
    timerPurple,
    accentPurple,
    accentPurpleLight,
    accentPurpleDark,
  },
};

export const lightTheme = {
  ...DarkTheme,
  colors: {
    ...DarkTheme.colors,
    tint: white,
    background: bg,
    backgroundSecondary: card,
    card,
    cardEmphasized,
    brand,
    brandDark,
    highEmText,
    midEmText,
    lowEmText,
    profitBg,
    profit,
    profitLight: primaryGreenLight,
    lossBg,
    loss,
    lossLight: primaryRedLight,
    primary,
    primaryTapped,
    onPrimary,
    secondary,
    secondaryTapped,
    onSecondary,
    segmentedControl,
    activeSegment,
    onActiveSegment,
    field,
    disabled,
    borderLight,
    border,
    borderEmphasized,
    borderProfit,
    borderLoss,
    tabActive,
    textPrimary: highEmText,
    textSecondary: midEmText,
    gradientRed,
    gradientOrange,
    gradientGreen,
    gradientGreenGlow,
    liquidLine: amber,
    liquidBorder: orangeDark,
    liquidBg: orangeDeep,
    timerPurple,
    accentPurple,
    accentPurpleLight,
    accentPurpleDark,
  },
};

// export const lightTheme = {
//   ...DefaultTheme,
//   colors: {
//     ...DefaultTheme.colors,
//     tint: primaryBlue,
//     background: lightBg,
//     backgroundSecondary: lightCard,
//     card: lightCard,
//     cardEmphasized: lightCardEmphasized,
//     brand: lightBrand,
//     brandDark,
//     highEmText: lightHighEmText,
//     midEmText: lightMidEmText,
//     lowEmText: lightLowEmText,
//     profitBg: lightProfitBg,
//     profit: lightProfit,
//     profitLight: primaryGreenDark,
//     lossBg: lightLossBg,
//     loss: lightLoss,
//     lossLight: primaryRedDark,
//     primary: lightPrimary,
//     primaryTapped: lightPrimaryTapped,
//     onPrimary: lightOnPrimary,
//     secondary: lightSecondary,
//     secondaryTapped: lightSecondaryTapped,
//     onSecondary: lightOnSecondary,
//     segmentedControl: lightSegmentedControl,
//     activeSegment: lightActiveSegment,
//     onActiveSegment: lightOnActiveSegment,
//     field: lightField,
//     disabled: lightDisabled,
//     borderLight: lightBorderLight,
//     border: lightBorder,
//     borderEmphasized: lightBorderEmphasized,
//     borderProfit: lightBorderProfit,
//     borderLoss: lightBorderLoss,
//     tabActive: lightTabActive,
//     textPrimary: lightHighEmText,
//     textSecondary: lightMidEmText,
//     gradientRed,
//     gradientOrange,
//     gradientGreen,
//     gradientGreenGlow,
//     liquidLine: lightLoss,
//     liquidBorder: lightLoss,
//     liquidBg: lightLossBg,
//   },
// };
