import { DarkTheme, DefaultTheme } from '@react-navigation/native';

import {
  activeSegment,
  bg,
  border,
  borderEmphasized,
  borderLight,
  borderLoss,
  borderProfit,
  brand,
  card,
  cardEmphasized,
  disabled,
  field,
  gradientGreen,
  gradientGreenGlow,
  gradientOrange,
  gradientRed,
  highEmText,
  lightActiveSegment,
  lightBg,
  lightBorder,
  lightBorderEmphasized,
  lightBorderLight,
  lightBorderLoss,
  lightBorderProfit,
  lightBrand,
  lightCard,
  lightCardEmphasized,
  lightDisabled,
  lightField,
  lightHighEmText,
  lightLoss,
  lightLossBg,
  lightLowEmText,
  lightMidEmText,
  lightOnActiveSegment,
  lightOnPrimary,
  lightOnSecondary,
  lightPrimary,
  lightPrimaryTapped,
  lightProfit,
  lightProfitBg,
  lightSecondary,
  lightSecondaryTapped,
  lightSegmentedControl,
  lightTabActive,
  loss,
  lossBg,
  lowEmText,
  midEmText,
  onActiveSegment,
  onPrimary,
  onSecondary,
  primary,
  primaryBlue,
  primaryGreenDark,
  primaryGreenLight,
  primaryRedLight,
  primaryTapped,
  profit,
  profitBg,
  secondary,
  secondaryTapped,
  segmentedControl,
  tabActive,
  white,
} from './app-colors';

export const lightTheme = {
  ...DefaultTheme,
  colors: {
    ...DefaultTheme.colors,
    tint: primaryBlue,
    background: lightBg,
    backgroundSecondary: lightCard,
    card: lightCard,
    cardEmphasized: lightCardEmphasized,
    brand: lightBrand,
    highEmText: lightHighEmText,
    midEmText: lightMidEmText,
    lowEmText: lightLowEmText,
    profitBg: lightProfitBg,
    profit: lightProfit,
    profitLight: primaryGreenDark,
    lossBg: lightLossBg,
    loss: lightLoss,
    lossLight: primaryRedLight,
    primary: lightPrimary,
    primaryTapped: lightPrimaryTapped,
    onPrimary: lightOnPrimary,
    secondary: lightSecondary,
    secondaryTapped: lightSecondaryTapped,
    onSecondary: lightOnSecondary,
    segmentedControl: lightSegmentedControl,
    activeSegment: lightActiveSegment,
    onActiveSegment: lightOnActiveSegment,
    field: lightField,
    disabled: lightDisabled,
    borderLight: lightBorderLight,
    border: lightBorder,
    borderEmphasized: lightBorderEmphasized,
    borderProfit: lightBorderProfit,
    borderLoss: lightBorderLoss,
    tabActive: lightTabActive,
    textPrimary: lightHighEmText,
    textSecondary: lightMidEmText,
    gradientRed,
    gradientOrange,
    gradientGreen,
    gradientGreenGlow,
  },
};

export const darkTheme = {
  ...DarkTheme,
  colors: {
    ...DarkTheme.colors,
    tint: white,
    background: bg,
    backgroundSecondary: card,
    card,
    cardEmphasized,
    brand,
    highEmText,
    midEmText,
    lowEmText,
    profitBg,
    profit,
    profitLight: primaryGreenLight,
    lossBg,
    loss,
    lossLight: primaryRedLight,
    primary,
    primaryTapped,
    onPrimary,
    secondary,
    secondaryTapped,
    onSecondary,
    segmentedControl,
    activeSegment,
    onActiveSegment,
    field,
    disabled,
    borderLight,
    border,
    borderEmphasized,
    borderProfit,
    borderLoss,
    tabActive,
    textPrimary: highEmText,
    textSecondary: midEmText,
    gradientRed,
    gradientOrange,
    gradientGreen,
    gradientGreenGlow,
  },
};
