export const badgeUrl =
  ' https://amgeuvathssbhopfvubw.supabase.co/storage/v1/object/sign/video-files/badge.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wMTU0NTY5Mi1kNzExLTQ1YjItOWIzNS0zOGFlMWNkYmM1MTEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlby1maWxlcy9iYWRnZS5tcDQiLCJpYXQiOjE3NTMxMjI0NzQsImV4cCI6MTc4NDY1ODQ3NH0.43KPmieNf9RKXdONISEm_0EvkjYQHsnAiC1c7t7Wi9U';

export const lowFireUrl =
  'https://amgeuvathssbhopfvubw.supabase.co/storage/v1/object/sign/video-files/Low%20Intensity%20Fire.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wMTU0NTY5Mi1kNzExLTQ1YjItOWIzNS0zOGFlMWNkYmM1MTEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlby1maWxlcy9Mb3cgSW50ZW5zaXR5IEZpcmUubXA0IiwiaWF0IjoxNzUzMTIyNTc1LCJleHAiOjE3ODQ2NTg1NzV9.DA829RrjAKWth3-yUtPtfUFwj9Ct4SdpG2K8duk6-9o';

export const midFireUrl =
  'https://amgeuvathssbhopfvubw.supabase.co/storage/v1/object/sign/video-files/Mid%20Intensity%20Fire.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wMTU0NTY5Mi1kNzExLTQ1YjItOWIzNS0zOGFlMWNkYmM1MTEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlby1maWxlcy9NaWQgSW50ZW5zaXR5IEZpcmUubXA0IiwiaWF0IjoxNzUzMTIyNjAyLCJleHAiOjE3ODQ2NTg2MDJ9.ZcU-gtIHSHFhRzDJ-9qbrhewecO-TUBh4JH8umP8DaE';

export const highFireUrl =
  'https://amgeuvathssbhopfvubw.supabase.co/storage/v1/object/sign/video-files/High%20Intensity%20Fire.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wMTU0NTY5Mi1kNzExLTQ1YjItOWIzNS0zOGFlMWNkYmM1MTEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlby1maWxlcy9IaWdoIEludGVuc2l0eSBGaXJlLm1wNCIsImlhdCI6MTc1MzEyMjYzMCwiZXhwIjoxNzg0NjU4NjMwfQ.gTPjwQ9InMu2y9msL2--usLUW3pBmHsaHyDX_Bw3PnA';

export const blueFlameUrl =
  'https://amgeuvathssbhopfvubw.supabase.co/storage/v1/object/sign/video-files/Blue%20flame.mp4?token=eyJraWQiOiJzdG9yYWdlLXVybC1zaWduaW5nLWtleV8wMTU0NTY5Mi1kNzExLTQ1YjItOWIzNS0zOGFlMWNkYmM1MTEiLCJhbGciOiJIUzI1NiJ9.eyJ1cmwiOiJ2aWRlby1maWxlcy9CbHVlIGZsYW1lLm1wNCIsImlhdCI6MTc1NTIwODAzMiwiZXhwIjoxODQ5ODE2MDMyfQ.sN02d0Wx_V60KtjhljQXWFSfVRzLMQLbzCNSv4x73hg';
